# Generated by Django 3.0.8 on 2020-09-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200927_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluser',
            name='Gender',
            field=models.BooleanField(choices=[(True, 'Male'), (False, 'Female')], default=None, null=True),
        ),
    ]
