# Generated by Django 3.0.8 on 2020-09-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200927_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluser',
            name='Gender',
            field=models.BooleanField(choices=[(True, 'Male'), (False, 'Female'), (None, 'Do not want to answer')], default=None, null=True),
        ),
    ]
